### ISSUE TITLE
Unresolved reference error

### ISSUE THREAD

**Issue by JeongJun-Lee** [typebrook/FiveMoreMinutes#22]
FiveMoreMinutes/app/src/main/kotlin/io/typebrook/fivemoreminutes/mapfragment/MapboxMapFragment.kt: (69, 42): Unresolved reference: LocationLayerPlugin

**Comment by typebrook** [comment]
Well...  [mapbox-plugins-android](https://github.com/mapbox/mapbox-plugins-android/) had huge changes in last two years and this repo is not maintained now

So you'd better go through examples in  mapbox-plugins-android by yourself to figure out how to use current API .
