### ISSUE TITLE
Unresolved reference: services

### ISSUE THREAD

**Issue by JeongJun-Lee** [typebrook/FiveMoreMinutes#23]
FiveMoreMinutes/app/src/main/kotlin/io/typebrook/fivemoreminutes/ui/ActivityUI.kt: (22, 19): Unresolved reference: services

Hello, I cloned this and build it at Android Studio 3.6.3. But I met two build errors including previous issue.

**Comment by typebrook** [comment]
Same, code for telemetry is moved to [`mapbox-android-core`](https://github.com/mapbox/mapbox-events-android).
